#!/usr/bin/env bash

if [[ ${1} =~ ^- ]]; then 
  _opt=${1} ; shift 
fi

[[ -z ${1} ]] && _path="./" || _path="${1}"

while true; do 
  CMD=$(find ${_path} -type f | awk '{print $2}' | fzf --print-query \
    --preview='bat -pn {}' --preview-window='up' \
    --border --info="inline-right" \
    --prompt="📂𝡻 " \
    ); 
  case ${CMD} in
    :exit|:quit|:q|:q!) exit ;;
    :edit) nvim ${0}         ;;
  esac

  if [[ ${CMD} =~ ${_path} ]]; then 
    [[ ${TERM_PROGRAM} == "tmux" ]] && tmux neww nvim ${CMD} || nvim ${CMD}
  fi

  case ${_opt} in
    '--quit') exit    ;;
  esac
done
